title: Xingyuan Chen
logo: /assets/img/headshot_1.png
description: MPhil in AI @ HKUST(GZ) 23' \n Stable, Explanable, and Fair Machien Learning \n xchen308@connect.hkust-gz.edu.cn
show_downloads: false
theme: jekyll-theme-minimal
