title: Xingyuan Chen
logo: /assets/img/headshot.png
description: MPhil in AI @ HKUST(GZ) 23' | Stable, Explanable, and Fair Machien Learning | xchen308@connect.hkust-gz.edu.cn
show_downloads: false
theme: jekyll-theme-minimal
